const HTTP_STATUS = {
  OK: 200,
  CREATED: 201,
  NO_CONTENT: 204,
  BAD_REQUEST: 400,
  UNAUTHORIZED: 401,
  FORBIDDEN: 403,
  NOT_FOUND: 404,
  TOO_MANY_REQUESTS: 429,
  CONFLICT: 409,
  UNPROCESSABLE: 422,
  INTERNAL_SERVER: 500,
};

const USER_ROLES = {
  USER: 'USER',
  ADMIN: 'ADMIN',
};

const SHELF_TYPES = {
  READ: 'READ',
  READING: 'READING',
  WISHLIST: 'WISHLIST',
  DROPPED: 'DROPPED',
};

const COOKIE_NAMES = {
  ACCESS_TOKEN: 'accessToken',
  REFRESH_TOKEN: 'refreshToken',
};

const GOAL_TYPES = {
  BOOKS: 'BOOKS',
  PAGES: 'PAGES',
};

const GOAL_STATUS = {
  ACTIVE: 'ACTIVE',
  COMPLETED: 'COMPLETED',
  FAILED: 'FAILED',
};

module.exports = {
  HTTP_STATUS,
  USER_ROLES,
  SHELF_TYPES,
  COOKIE_NAMES,
  GOAL_TYPES,
  GOAL_STATUS,
};
